language: minimal
sudo: false

env:
  - NAME=graalvm8 BASE_IMAGE=lustefaniak/graalvm:8-19.3.0 SBT_VERSION=1.3.6 SCALA_VERSION=2.12.10
  - NAME=graalvm8 BASE_IMAGE=lustefaniak/graalvm:8-19.3.0 SBT_VERSION=1.3.6 SCALA_VERSION=2.13.1
  - NAME=graalvm8 BASE_IMAGE=lustefaniak/graalvm:8-19.3.0 SBT_VERSION=1.2.8 SCALA_VERSION=2.12.10
  - NAME=graalvm8 BASE_IMAGE=lustefaniak/graalvm:8-19.3.0 SBT_VERSION=1.2.8 SCALA_VERSION=2.13.1
  - NAME=graalvm11 BASE_IMAGE=lustefaniak/graalvm:11-19.3.0 SBT_VERSION=1.3.6 SCALA_VERSION=2.12.10
  - NAME=graalvm11 BASE_IMAGE=lustefaniak/graalvm:11-19.3.0 SBT_VERSION=1.3.6 SCALA_VERSION=2.13.1
  - NAME=graalvm11 BASE_IMAGE=lustefaniak/graalvm:11-19.3.0 SBT_VERSION=1.2.8 SCALA_VERSION=2.12.10
  - NAME=graalvm11 BASE_IMAGE=lustefaniak/graalvm:11-19.3.0 SBT_VERSION=1.2.8 SCALA_VERSION=2.13.1
services:
  - docker

script:
  - bash build.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    tags: true
