language: minimal
sudo: false

env:
  - BASE=graalvm SBT_VERSION=1.2.8 SCALA_VERSION=2.12.7
  - BASE=graalvm SBT_VERSION=1.2.8 SCALA_VERSION=2.12.8

services:
  - docker

script:
  - bash build.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master