language: minimal
sudo: false

env:
  - NAME=graalvm BASE_IMAGE=lustefaniak/docker-graalvm:alpine-1.0.0-rc15.0 SBT_VERSION=1.2.8 SCALA_VERSION=2.12.8
  - NAME=adoptopenjdk8 BASE_IMAGE=adoptopenjdk/openjdk8:jre8u202-b08-alpine SBT_VERSION=1.2.8 SCALA_VERSION=2.12.8
  - NAME=adoptopenjdk8-jdk-slim BASE_IMAGE=adoptopenjdk/openjdk8:jdk8u202-b08-alpine-slim SBT_VERSION=1.2.8 SCALA_VERSION=2.12.8
  - NAME=adoptopenjdk11 BASE_IMAGE=adoptopenjdk/openjdk11:jre-11.0.2.9-alpine SBT_VERSION=1.2.8 SCALA_VERSION=2.12.8
  - NAME=adoptopenjdk11-jdk-slim BASE_IMAGE=adoptopenjdk/openjdk11:jdk-11.0.2.9-alpine-slim SBT_VERSION=1.2.8 SCALA_VERSION=2.12.8


services:
  - docker

script:
  - bash build.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    tags: true