language: minimal
sudo: false

env:
  - NAME=graalvm BASE_IMAGE=lustefaniak/docker-graalvm:alpine-19.2.0.1 SBT_VERSION=1.3.0 SCALA_VERSION=2.12.10
  - NAME=graalvm BASE_IMAGE=lustefaniak/docker-graalvm:alpine-19.2.0.1 SBT_VERSION=1.3.0 SCALA_VERSION=2.13.1
  - NAME=graalvm BASE_IMAGE=lustefaniak/docker-graalvm:alpine-19.2.0.1 SBT_VERSION=1.2.8 SCALA_VERSION=2.12.10
  - NAME=graalvm BASE_IMAGE=lustefaniak/docker-graalvm:alpine-19.2.0.1 SBT_VERSION=1.2.8 SCALA_VERSION=2.13.1  

  - NAME=adoptopenjdk8 BASE_IMAGE=adoptopenjdk/openjdk8:jre8u222-b10-alpine SBT_VERSION=1.3.0 SCALA_VERSION=2.12.10
  - NAME=adoptopenjdk8 BASE_IMAGE=adoptopenjdk/openjdk8:jre8u222-b10-alpine SBT_VERSION=1.3.0 SCALA_VERSION=2.13.1

  - NAME=adoptopenjdk8-jdk-slim BASE_IMAGE=adoptopenjdk/openjdk8:jdk8u222-b10-alpine-slim SBT_VERSION=1.3.0 SCALA_VERSION=2.12.10
  - NAME=adoptopenjdk8-jdk-slim BASE_IMAGE=adoptopenjdk/openjdk8:jdk8u222-b10-alpine-slim SBT_VERSION=1.3.0 SCALA_VERSION=2.13.1

  - NAME=adoptopenjdk11 BASE_IMAGE=adoptopenjdk/openjdk11:jre-11.0.4_11-alpine SBT_VERSION=1.3.0 SCALA_VERSION=2.12.10
  - NAME=adoptopenjdk11 BASE_IMAGE=adoptopenjdk/openjdk11:jre-11.0.4_11-alpine SBT_VERSION=1.3.0 SCALA_VERSION=2.13.1

  - NAME=adoptopenjdk11-jdk-slim BASE_IMAGE=adoptopenjdk/openjdk11:jdk-11.0.4_11-alpine-slim SBT_VERSION=1.3.0 SCALA_VERSION=2.12.10
  - NAME=adoptopenjdk11-jdk-slim BASE_IMAGE=adoptopenjdk/openjdk11:jdk-11.0.4_11-alpine-slim SBT_VERSION=1.3.0 SCALA_VERSION=2.13.1


services:
  - docker

script:
  - bash build.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    tags: true
