name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker:
          - "NAME=graalvm8 BASE_IMAGE=lustefaniak/graalvm:8-20.2.0-da3a89f4b20c1098726188961b3ea20aa28191aa"
          - "NAME=graalvm11 BASE_IMAGE=lustefaniak/graalvm:11-20.2.0-da3a89f4b20c1098726188961b3ea20aa28191aa"
          - "NAME=adoptopenjdk8 BASE_IMAGE=adoptopenjdk/openjdk8:jdk8u232-b09-alpine-slim"
          - "NAME=adoptopenjdk11 BASE_IMAGE=adoptopenjdk/openjdk11:jdk-11.0.5_10-alpine-slim"
        sbt: [1.4.2]
        scala: [2.13.3, 2.12.12]
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: ${{ matrix.docker }} SBT_LAUNCHER_VERSION=1.4.2 SBT_VERSION=${{ matrix.sbt }} SCALA_VERSION=${{ matrix.scala }} VERSION=${{ github.sha }} ./build.sh
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u lustefaniak --password-stdin
      - name: Push from master
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            ${{ matrix.docker }} SBT_VERSION=${{ matrix.sbt }} SCALA_VERSION=${{ matrix.scala }} VERSION=${{ github.sha }} ./push.sh
          else
            echo "Not master branch, skipping..."
          fi
